[김가람휘] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/30-westagram-backend-3-team pull request #11
Opened 2022-02-18 00:11 UTC by kimkaramhwi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 뷰 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일이나 패스워드가 전달되지 않을 경우 KeyError 반환
- 이메일에 @와 .이 포함되지 않을 경우 INVALID EMAIL 반환
- 비밀번호가 8자리 이상, 문자, 숫자, 특수문자의 복합이 아닐경우 INVALID PASSWORD 반환
- 같은 이메일 등록 시 EXISTING USER 반환
- 회원가입 성공 시 SUCCESS 반환하고 DB에 회원정보 저장

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 모델을 수정하면서 추가한 created_at, updated_at 부분을 인식하지 못하는 것 같아 migratios 폴더의 파일들을 수정하였는데 merge했을 때 충돌이 생기지 않을까 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-18 07:07 UTC, kyeongraekim requested changes
아래 내용 참고하여 수정 반영 및 코멘트 남겨주세요!~

2022-02-18 07:07 UTC, kyeongraekim commented on students/westagram/users/models.py
> +    email      = models.EmailField(max_length=250, unique=True)
실제 현업에 나가시면 모델에 대한 수정은 feature 모델 브랜치를 새로 파서 기능별로 푸시를 진행해주셔야된다는 점 기억해주세요!~

2022-02-18 07:07 UTC, kyeongraekim commented on students/westagram/users/validation.py
> +    password_regex = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
해당 정규표현식이 전반적으로 어떤 의미를 담고 있는지 아래 코멘트를 남겨주실 수 있으실까요?

2022-02-18 07:07 UTC, kyeongraekim commented on students/westagram/users/views.py
> +            if User.objects.filter(email = email).exists():
좀 전에 여쭈어 본 .exists()를 쓰는 이점이 무엇이 있을까요?

그리고 아래의 파이썬 문법은 어떤 리턴 값을 낼지 고민해보시고 파이썬 if 문법을 좀 더 리서치 해보세요!

```python 

xxx = 30기 
if xxx:
  return False

2022-02-18 07:07 UTC, kyeongraekim commented on students/westagram/users/views.py
> +            contact  = data['contact']
실제 인스타 그램 기획상 이메일을 제공했다면 contact나 username은 꼭 기입되어야 할 데이터가 될 수도, 안될 수도 있겠네요 ㅎㅎ
현재 꼭 들어가야만 하는 기획으로 구조를 짜주셨는데 혹시 안들어가도 되는 경우를 username을 기준으로 설정해보세요!

2022-02-18 07:13 UTC, kimkaramhwi commented on students/westagram/users/models.py
> +    email      = models.EmailField(max_length=250, unique=True)
넵!

2022-02-18 07:40 UTC, kimkaramhwi commented on students/westagram/users/validation.py
> +    password_regex = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
최소 8 글자 이상, 최소 한 개의 문자와 숫자 그리고 특수 문자를 포함해야 합니다.
-> ^(?=.*[A-Za-z]) : 문자의 집합 안에서 최소 한 개 이상, 
(?=.*\d) : 숫자에서 최소 한 개 이상,
(?=.*[$@$!%*#?&]) : 
[A-Za-z\d$@$!%*#?&]{8,}$ :

2022-02-18 07:46 UTC, kimkaramhwi commented on students/westagram/users/views.py
> +            if User.objects.filter(email = email).exists():
xxx에 값이 있으므로 if문에서는 True로 판단하여 False를 반환합니다.
따라서 exists()를 쓰지 않아도 filter만으로 True와 False를 반환해낼 수 있습니다. 실제로 지우고 실행했을 때 잘 돌아갔습니다. 하지만 exists()

2022-02-21 01:08 UTC, kyeongraekim commented
LGTM!~ 고생하셨습니다. 이어서 주말간 작업한 내용 깃 헙 플로우 잘 관리해주시면서 올려주세요!~

2022-02-21 01:09 UTC, merged