[김광일] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/30-westagram-backend-3-team pull request #12
Opened 2022-02-18 08:14 UTC by Kimgwangil

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일에 `@`, `.` 빠졌을 때, 동일 이메일이 존재할 때, 비밀번호에 숫자, 문자, 특수문자가 모두 들어있지 않을 때 에러 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- phone_number의 경우 국가번호가 추가되는 상황이 생기면 길이가 다 다를텐데 번호를 잘못 기입한 사람과 구분하는 방법은?
  - 첫글자로 확인하면 될까? 
- 이메일과, 비밀번호가 둘 다 에러인 상황에서는 더 먼저 사용한 If 문이 반환이 될텐데, 실제로는 둘 다 반영이 되어야하는 것이 아닌가?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-18 08:35 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정해주세요!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/urls.py
> +# http://127.0.0.1:8000/users/
코드 진행상 불필요한 주석은 제거해주세요!~

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/urls.py
> +    path('', UserView.as_view())
회원 가입에 해당되는 url이 적혀있어야 될 것으로 보이네요! 그렇다면 뒤에 UserView로 임포트한 부분도 클래스 명을 회원가입이 명시될 수 있게 변경해주셔야겠죠?

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/validation.py
> +    email_regex = re.compile(r"^([0-9a-zA-Z]?[+-_.]?[0-9a-zA-Z])+@[a-zA_Z-]+[.][a-zA_Z-]+$")
- 정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 compile()해서 사용하지 않고, match()를 사용하는 것을 공식 문서에서 추천하고 있습니다. 해당 정규표현식에서 complie 용법이 꼭 필 요한 지 한 번 고민해보세요!~
- 정규표현식은 상수 데이터로서 네이밍 컨벤션에 따라서 대문자로 변경해주세요!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +from .validation  import email_validation, password_validation
컨벤션에 맞게 임포트 하는 출처에 맞게 스페이싱 구분을 해주세요!
그리고 실제 코드상에서 사용하지 않는 임포트문은 삭제해주세요!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +                return JsonResponse( {"message" : "INVALID_EMAIL❌"}, status = 403)
이모티콘을 이모지로 작성해주셨는데 모든 인터넷 환경에서 사용가능할 것 이라고는 보여지지 않습니다. 라틴어 계열의 영어를 사용해서 예기치 못할 내용을 미연에 방지해주세요!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +class UserView(View):
클래스 명 변경 소요 urls.py 에서 언급드렸습니다!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +            if email_validation == False:
== False 라는 내용이 부연으로 첨가 되어야 될까요? 
파이썬 문법에서 if xxx  가 내어주는 예상 리턴값이 무엇인지 한 번 고민해보세요!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +            if User.objects.filter(email = email).exists():
이곳에서 exists()를 사용하신 이유와 그로 인해 얻어지는 이점이 무엇인지 한 번  아래 코멘트로 설명해주세요!

2022-02-18 08:35 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +    def get(self, request):
회원가입에 불필요한 get 함수 코드가 같이 딸려 들어왔습니다. 기능별로 소스코드를 올려야하는 깃헙 사용법에 입각하여 푸시해주세요!

2022-02-18 09:08 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +class UserView(View):
다만 만일 한 클래스 안에서 두개의 함수로 분기를 계획하신 거라면 아래 코멘트를 남겨 주세요! 그리고 두 개의 클래스로 나누는 경우와 한 클래스에서 두 함수로 나누는 부분에 대해 어떠한 부분을 의도하였고 그 사유가 무엇이었는지 코멘트로 남겨주세요!

2022-02-18 11:24 UTC, Kimgwangil commented on students/gwangil/users/urls.py
> +# http://127.0.0.1:8000/users/
네~!

2022-02-18 11:57 UTC, Kimgwangil commented on students/gwangil/users/views.py
> +            if User.objects.filter(email = email).exists():
- 제가 exists()를 사용한 이유 : 위의 `if xxx 의 결과값은 무엇이 나오는가?` 와 이어지는 부분이라고 생각되는데, if xxx만 사용하였을 때 확실한 결과값이나, 그 값이 나올 수 있는 조건을 걸어줘야만 한다고 생각했습니다. 
때문에 exists()를 써야만 filter 안에 있는 email의 값이 존재하는지 참 거짓을 판별할 수 있다고 생각해서 사용하였습니다.

- 여기서 제가 잊고 있었던 것 : if 안에 참과 거짓을 지정해주지 않더라도, 1 = True, 0 = False로 인식을 한다.

- 그렇다면 내가 이해한 exist()를 사용하는 목적 : filter는 해당하는 값을 찾아서 데리고 오는 것이고, exists()는 해당 값을 찾으면 찾았다는 사실만을 가지고 돌아오기 때문에 속도가 더 빠르다.

2022-02-18 11:58 UTC, Kimgwangil commented on students/gwangil/users/views.py
> +            if email_validation == False:
if xxx 의 경우 0 = False, '' = False (빈 값) / 값이 있으면 True를 반환합니다.

2022-02-18 12:05 UTC, Kimgwangil commented on students/gwangil/users/views.py
> +class UserView(View):
`회원 정보를 받고 관리자가 그 정보를 찍어볼 수 있어야하지 않나?` 라는 생각으로 `post`와 `get`으로 분기를 하였습니다.
제가 회원가입의 특성을 제대로 이해하지 못한 것 같습니다.

2022-02-18 12:14 UTC, Kimgwangil commented on students/gwangil/users/urls.py
> +    path('', UserView.as_view())
넵! 확인했습니다!

2022-02-18 12:16 UTC, Kimgwangil commented on students/gwangil/users/validation.py
> +    email_regex = re.compile(r"^([0-9a-zA-Z]?[+-_.]?[0-9a-zA-Z])+@[a-zA_Z-]+[.][a-zA_Z-]+$")
변수명을 지정하고 그를 사용함이 맞는 방법이라고 생각하였는데, 반복되지 않는 상황에 사용하는 것은 적절하지 않아보입니다!

2022-02-18 12:16 UTC, Kimgwangil commented on students/gwangil/users/views.py
> +                return JsonResponse( {"message" : "INVALID_EMAIL❌"}, status = 403)
앗  제 화면에 보인다고 다 표현이 되는 것이 아니었네요.. 감사합니다!

2022-02-21 01:12 UTC, kyeongraekim approved these changes
LGTM!~ 이어서 차례로 작업한 내용 깃 플로우에 유의하며 차례로 푸시해주세요!

2022-02-21 01:12 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +            if User.objects.filter(email = email).exists():
열심히 잘 리서치 해주셨네요!~

2022-02-21 01:12 UTC, merged