[김가람휘] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/30-westagram-backend-3-team pull request #24
Opened 2022-02-21 08:34 UTC by kimkaramhwi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 성공시 JWT의 payload에 로그인 한 user의 id를 담아서 발급
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- bcrypt의 checkpw method를 이용하여 비밀번호 확인 로직 추가
- 로그인 성공시 JWT를 응담의 데이터로 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 08:39 UTC, YEONG-CTRL commented on students/westagram/users/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
password를 encode해서 둘다 byte 형태로 만들어줘야 되네요! 고민하고 있었는데 감사합니다

2022-02-21 08:50 UTC, kimkaramhwi commented on students/westagram/users/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
도움이 되셨다니 다행입니다!

2022-02-21 09:52 UTC, kyeongraekim requested changes
아래 내용 확인해보시고 수정을 고민해보세요!~

2022-02-21 09:52 UTC, kyeongraekim commented on students/westagram/users/views.py
> +                jwt_token = jwt.encode({'id':user.id}, SECRET_KEY, ALGORITHM)
해당 내용의 변수명은 jwt 보다 목적과 기능이 명시된 access_token이 나을 것 같습니다~

2022-02-21 09:52 UTC, kyeongraekim commented on students/westagram/users/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
앞에 클라이언트 단에서 넘어온 password와 뒤에 디에서 꺼내온 password를 조금 더 명확히 분리 시키기 위해 hashed_password라는 변수명에 뒷 내용을 담아서 비교해 보는 것은 어떨까요?

2022-02-21 09:52 UTC, kyeongraekim commented on students/westagram/users/views.py
> +                return JsonResponse({'messasge':'SUCCESS', 'jwt_token':jwt_token.decode('utf-8')}, status=200)
token에 담길 값에 대한 utf-8 decoding이 꼭 필요한지 다시 한 번 고민해보세요!~

2022-02-21 10:53 UTC, kimkaramhwi commented on students/westagram/users/views.py
> +                jwt_token = jwt.encode({'id':user.id}, SECRET_KEY, ALGORITHM)
넵 수정하겠습니다!

2022-02-21 10:58 UTC, kimkaramhwi commented on students/westagram/users/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
넵 알겠습니다!

2022-02-21 11:02 UTC, kimkaramhwi commented on students/westagram/users/views.py
> +                return JsonResponse({'messasge':'SUCCESS', 'jwt_token':jwt_token.decode('utf-8')}, status=200)
byte형식 그대로 db에 저장해도 상관없을 것 같지만 decode를 쓰지 않으면 제 로컬 컴퓨터에서는 다음과 같은 에러가 발생하는데 그 이유가 궁금합니다!

TypeError: Object of type bytes is not JSON serializable

2022-02-22 01:42 UTC, kyeongraekim requested changes
아래내용 확인하여 수정해주세요!~

2022-02-22 01:42 UTC, kyeongraekim commented on students/westagram/users/views.py
> +                return JsonResponse({'messasge':'SUCCESS', 'access_token':access_token.decode('utf-8')}, status=200)
- 제가 지난 코멘트로 의도 드렸던 내용은 return 값 내부에서 decode를 하는 것보다 윗줄에 access_token 변수값 뒤에 붙여주는 것 이었습니다~ 기능상에 큰 차이보다 가독성 선에서 더 깔끔해 보일 것 같네요!~

- 그리고 질문 주셨던 내용에 대해서 힌트를 드리고자 하는데 shell 에서 직접 다음의 실험을 한 번 해보세요! 라운지 시간에 한 번 보러 가겠습니다!

(1) http 통신을 통해서 db 안에 byte 형태와 string 형태로 비밀번호 저장
(2) python manage.py shell을 실행, 두 비밀번호의 db상 저장되기 전의 type을 확인
(3) python manage.py shell을 실행, 두 비밀번호의 db상 저장된 후의 type을 확인
(4) 두 비밀번호를 user.password 형식으로 불러온 후 실제 어떤 형식으로 나오는지 확인

위 내용을 통해서 충분히 byte 타입으로 저장하면 hashpw 가 정상작동이 되지 않는 이유를 파악하실 수 있으실거에요!
그리고 byte string이 json format 에 적합한 데이터 타입인지에 대한 추가 리서치를 해보세요!

2022-02-22 06:00 UTC, kimkaramhwi commented on students/westagram/users/views.py
> +                return JsonResponse({'messasge':'SUCCESS', 'access_token':access_token.decode('utf-8')}, status=200)
PyJWT버전 차이로 인해 제 코드에서 decode를 사용하지 않으면 password가 바이트 형식이라서 db에 저장이 되지 못하는 오류가 생겼습니다.

최신 버전을 깔아서 사용하니 decode하지 않아도 자동으로 string형식으로 암호화된 password가 db에 잘 저장되었습니다!

2022-02-22 06:31 UTC, kyeongraekim commented on students/westagram/users/views.py
> +                return JsonResponse({'messasge':'SUCCESS', 'access_token':access_token.decode('utf-8')}, status=200)
네 가람님 충분한 고민의 흔적이 보이는 것 같습니다! LGTM!~

2022-02-22 06:32 UTC, kyeongraekim approved these changes

2022-02-22 06:33 UTC, kyeongraekim commented
가람님 미션 6까지 수행해주시느라 고생 많으셨습니다!~ 다음 미션을 바로 건너가기보다 지금까지 진행한 내용 중 파이썬, 장고, 깃, 마이그레이션 등 관련 새롭게 알게 된 지식, 개발자로서의 마인드, 미래에 조심해야할 점들 등에 대해서 `꼭 자세한 블로깅을` 해보세요!

2022-02-22 06:33 UTC, merged