[김광일] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/30-westagram-backend-3-team pull request #33
Opened 2022-02-22 10:35 UTC by Kimgwangil

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 JWT 발급
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 JWT 발급
- 
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-22 10:57 UTC, YEONG-CTRL commented on students/gwangil/users/views.py
> +from my_settings  import SECRET_KEY, ALGORITHM
ALGORITHM은 상수니까 컨벤션 상 대문자로 해주는 것이 맞겠네요! 잘봤습니다.

2022-02-22 12:22 UTC, kyeongraekim requested changes

2022-02-22 12:22 UTC, kyeongraekim commented on students/gwangil/users/views.py
>                  if not password_validation(password):
이번에 올라온 PR은 아니지만 ㅎㅎ 코멘트 소요가 보여서 남깁니다!~ 불필요한 if-else 의 분기는 코드의 연산을 느리게 만듭니다. 중첩의 조건절은 불필요해보이니 한 번 수정해보세요!~

2022-02-22 12:22 UTC, kyeongraekim commented on students/gwangil/users/views.py
> +            user = User.objects.get(email = email)
다양한 변수가 작용하는 코드에서 위 filter 로는 쿼리셋이 나올 수 있고 현재 라인에서의 get 메소드로는 하나의 객체가 나오게 되어 있습니다.  필터 메소드를 통해서 나올 수 있는 다양한 객체에 대해서 django exception 문을 걸어서 에러 핸들링을 사전에 해보세요!~ 
참고링크: https://www.kite.com/python/docs/django.core.exceptions.MultipleObjectsReturned

2022-02-23 02:36 UTC, Kimgwangil commented on students/gwangil/users/views.py
>                  if not password_validation(password):
email과 password 가 둘 다 틀렸을 경우를 고려햐여서 if (둘 다 틀렸을 떄 )/ elif (email만) / elif (password만) 으로 하는 것이 맞을지, 
여느 웹사이트처럼 둘 중 하나만 틀렸을 때만 구현을 하는 것이 맞을지 고민이 되네요..

2022-02-23 02:38 UTC, Kimgwangil commented on students/gwangil/users/views.py
> +            user = User.objects.get(email = email)
쿼리가 하나 이상의 객체를 반환할 떄 생길 수 있는 MultipleObjectsReturned 와 get 이나 exists()에 해당하는 내용이 없을 때 발생할 수 있는 DoesNotExist를 적용해봤습니다.  이 두 에러에 대해서는 더 찾아보고 블로깅할 예정입니다.

2022-02-23 11:21 UTC, Kimgwangil commented on students/gwangil/users/views.py
> +from my_settings  import SECRET_KEY, ALGORITHM
영서님 덕분에 `상수` = `변하지 않는 값` 이라는 사실을 다시 한번 기억하고 갑니다!

2022-02-24 08:53 UTC, kyeongraekim approved these changes

2022-02-24 08:53 UTC, merged